### ISSUE TITLE
ERROR: lazy loading failed for package ‘HumanLiver’

### ISSUE THREAD

**Issue by eviho** [BaderLab/HumanLiver#5]
Dear all,

I am having issues to install the "HumanLiver" package.
I am running the newest version of R (4.0.0) on MacOS and all the packages are also updated.

`> devtools::install_github("BaderLab/HumanLiver")
Downloading GitHub repo BaderLab/HumanLiver@master
✓  checking for file ‘/private/var/folders/yn/tbw3r2xn0m94qrwvh1h16mnw0000gn/T/Rtmp3cE6pF/remotes10e17b3a97b/BaderLab-HumanLiver-39c873b/DESCRIPTION’ ...
─  preparing ‘HumanLiver’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  ‘HumanLiver/inst/liver/HumanLiver.RData’
─  building ‘HumanLiver_1.5.0.tar.gz’
   
* installing *source* package ‘HumanLiver’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
sh: line 1:  4621 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/yn/tbw3r2xn0m94qrwvh1h16mnw0000gn/T//RtmpcNy9lM/file120675b2df47'
ERROR: lazy loading failed for package ‘HumanLiver’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/HumanLiver’
installation of package ‘/var/folders/yn/tbw3r2xn0m94qrwvh1h16mnw0000gn/T//Rtmp3cE6pF/file10e1243bce30/HumanLiver_1.5.0.tar.gz’ had non-zero exit status`

As you can see the installation fails and I am not sure why. Do you have an idea what the problem could be?

Thank you.
Best regards,
E. Viho

**Comment by innesbre** [comment]
Hi Eva,
Unfortunately I'm struggling to recreate your error, but I have a solution.  Instead of installing this package, follow the instructions [here](http://shiny.baderlab.org/HumanLiverAtlas/) to download the data file and run it locally using scClustViz.
